# Script para desenvolvimento local
version: '3.8'

services:
  # Banco de dados MongoDB (apenas para desenvolvimento)
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: clinic_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: clinic123
      MONGO_INITDB_DATABASE: agendamento
    ports:
      - "27018:27017"  # Porta diferente para não conflitar com MongoDB local
    volumes:
      - mongodb_data_dev:/data/db
      - mongodb_config_dev:/data/configdb
    networks:
      - clinic_network

  # Interface web do MongoDB (opcional)
  mongo-express:
    image: mongo-express:latest
    container_name: clinic_mongo_express_dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: clinic123
      ME_CONFIG_MONGODB_URL: mongodb://admin:clinic123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: clinic123
    depends_on:
      - mongodb
    networks:
      - clinic_network

volumes:
  mongodb_data_dev:
    driver: local
  mongodb_config_dev:
    driver: local

networks:
  clinic_network:
    driver: bridge
